// auth types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

// alert types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//RDPS types
export const FETCH_RDPSDATA = "FETCH_RDPSDATA"
export const GET_RDP = "GET_RDP"
export const FETCH_RDPSSELECTOPTIONS = "FETCH_RDPSSELECTOPTIONS"
export const ADD_RDPSDATA = "ADD_RDPSDATA"
export const EDIT_RDPSDATA = "EDIT_RDPSDATA"

//VPS types
export const FETCH_VPSDATA = "FETCH_VPSDATA"
export const GET_VPS = "GET_VPS"
export const FETCH_VPSSELECTOPTIONS = "FETCH_VPSSELECTOPTIONS"
export const ADD_VPSDATA = "ADD_VPSDATA"
export const EDIT_VPSDATA = "EDIT_VPSDATA"

//CPANEL types
export const FETCH_CPANELDATA = "FETCH_CPANELDATA"
export const GET_CPANEL = "GET_CPANEL"
export const FETCH_CPANELSELECTOPTIONS = "FETCH_CPANELSELECTOPTIONS"
export const ADD_CPANELDATA = "ADD_CPANELDATA"
export const EDIT_CPANELDATA = "EDIT_CPANELDATA"

//SHELL types
export const FETCH_SHELLDATA = "FETCH_SHELLDATA"
export const GET_SHELL = "GET_SHELL"
export const FETCH_SHELLSELECTOPTIONS = "FETCH_SHELLSELECTOPTIONS"
export const ADD_SHELLDATA = "ADD_SHELLDATA"
export const EDIT_SHELLDATA = "EDIT_SHELLDATA"

//SMTP types
export const FETCH_SMTPDATA = "FETCH_SMTPDATA"
export const GET_SMTP = "GET_SMTP"
export const FETCH_SMTPSELECTOPTIONS = "FETCH_SMTPSELECTOPTIONS"
export const ADD_SMTPDATA = "ADD_SMTPDATA"
export const EDIT_SMTPDATA = "EDIT_SMTPDATA"

//PHPMAILER types
export const FETCH_PHPMAILERDATA = "FETCH_PHPMAILERDATA"
export const GET_PHPMAILER = "GET_PHPMAILER"
export const FETCH_PHPMAILERSELECTOPTIONS = "FETCH_PHPMAILERSELECTOPTIONS"
export const ADD_PHPMAILERDATA = "ADD_PHPMAILERDATA"
export const EDIT_PHPMAILERDATA = "EDIT_PHPMAILERDATA"

//LEAD types
export const FETCH_LEADDATA = "FETCH_LEADDATA"
export const GET_LEAD = "GET_LEAD"
export const FETCH_LEADSELECTOPTIONS = "FETCH_LEADSELECTOPTIONS"
export const ADD_LEADDATA = "ADD_LEADDATA"
export const EDIT_LEADDATA = "EDIT_LEADDATA"

//PREMIUMSHOP types
export const FETCH_PREMIUMSHOPDATA = "FETCH_PREMIUMSHOPDATA"
export const GET_PREMIUMSHOP = "GET_PREMIUMSHOP"
export const FETCH_PREMIUMSHOPSELECTOPTIONS = "FETCH_PREMIUMSHOPSELECTOPTIONS"
export const ADD_PREMIUMSHOPDATA = "ADD_PREMIUMSHOPDATA"
export const EDIT_PREMIUMSHOPDATA = "EDIT_PREMIUMSHOPDATA"

//PROGRAMSCRIPT types
export const FETCH_PROGRAMSCRIPTDATA = "FETCH_PROGRAMSCRIPTDATA"
export const GET_PROGRAMSCRIPT = "GET_PROGRAMSCRIPT"
export const FETCH_PROGRAMSCRIPTSELECTOPTIONS = "FETCH_PROGRAMSCRIPTSELECTOPTIONS"
export const ADD_PROGRAMSCRIPTDATA = "ADD_PROGRAMSCRIPTDATA"
export const EDIT_PROGRAMSCRIPTDATA = "EDIT_PROGRAMSCRIPTDATA"

//SERVICE types
export const SERVICE = "SERVICE";

//METHOD types
export const FETCH_METHODDATA = "FETCH_METHODDATA"
export const GET_METHOD = "GET_METHOD"
export const FETCH_METHODSELECTOPTIONS = "FETCH_METHODSELECTOPTIONS"
export const ADD_METHODDATA = "ADD_METHODDATA"
export const EDIT_METHODDATA = "EDIT_METHODDATA"

//App types
export const APP_LOADING = "APP_LOADING"
export const APP_LOADING_END = "APP_LOADING_END"

// User types
export const FETCH_USERS = 'FETCH_USERS';
export const USER_CHANGE_STATUS = 'USER_CHANGE_STATUS';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
